### ISSUE TITLE
Malformed json files starting ~dump-block-3193000.json

### ISSUE THREAD

**Issue by afragapane** [NeoResearch/neo-storage-audit#3]
I have been using the neo-storage-audit to perform a full audit of storage on the neo-one/neotracker node.  First, thank you for making this repo available, it has been a great help!

I have noticed that starting around the file `dump-block-3193000.json`, the entries are not well-formed json and are therefore not parsable by standard JSON reading utilities.  Commas are often missing between entries and entries themselves are often also truncated, missing comas, or missing closing braces (`}`, `]`).

Here are the first few files which display the issue, although the pattern seems to continue:
dump-block-3193000.json
dump-block-3194000.json
dump-block-3195000.json
dump-block-3196000.json
dump-block-3197000.json
dump-block-3198000.json
dump-block-3199000.json
dump-block-3120000.json  

Do you know why these files are like this and are they possible to fix?
Thanks again!

@dicarlo2

**Comment by afragapane** [comment]
Actually, it looks like I may have been working with an outdated version of this repo.  It looks like these files were recently fixed.  My mistake!  Thank you!

**Comment by vncoelho** [comment]
Hi @afragapane, thanks for informing.
Maybe it because we merge this file using this script here: https://github.com/NeoResearch/neo-tests/blob/master/simple-rpc-node/merge_Storage.sh

Usually, we dump it in batches of 1000. However, in order to avoid the lost of data if the node crashes we persist every block when it is syncing from the P2P.

Furthermore, there might be some problem, because just recently we updated the plugin to throw an exception and avoid commit the block if it crashes.

**Comment by vncoelho** [comment]
Anhhhhhhhh, I thought that I had closed that with my comment. AHEUahue
We commented at the same time.
